version: "3.9"

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
       MONGO_URL: 
    ports: ${DATABASE}
      - 

  db:
    image: mongo
    container_name: 
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    ports:
      - "27017:27017"
